### ISSUE TITLE
What's version of cocos2d, piglet and pymunk in your project? I had a problem try run your game

### ISSUE THREAD

**Issue by nenodias** [davexunit/PyPlatformer#1]

**Comment by davexunit** [comment]
So, I haven't worked on this since November, 2011, and in fact I don't really use Python anymore.  I don't remember which versions of the libraries I was using at the time.  If you post the backtrace here, I could attempt to point you in the right direction, if you're still interested.

Note that this **isn't** a real game, but a rather simplistic example of a basic side scrolling game with 2D physics.  Maybe some of the code snippets would be useful to you if you're trying to write your own game.  I see that I did some entity/component stuff and included a Tiled TMX loader (who knows if that still works for the current version of the TMX format).

FWIW, all of my current game development experiments are for Sly, written in the Scheme programming language.  http://dthompson.us/pages/software/sly.html
